# SPDX-FileCopyrightText: Fondazione Istituto Italiano di Tecnologia
#
# SPDX-License-Identifier: BSD-3-Clause


def measurementControl(linkMass, linkDimensions):

    print(
        "\n|-----------------------------------------------------------|",
        "\n|          Anthropometric information table links           |",
        "\n|-----------------------------------------------------------|",
        "\n|         Link          |   Mass[Kg]  |    Dimensions[m]    |",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Head                   |",
        str(round(linkMass["Head_mass"], 2)).ljust(11),
        "|",
        "d: ",
        str(round(linkDimensions["Head_x"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Neck                   |",
        str(round(linkMass["Neck_mass"], 2)).ljust(11),
        "|",
        "d: ",
        str(round(linkDimensions["Neck_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "l: ",
        str(round(linkDimensions["Neck_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Upper Trunk            |",
        str(round(linkMass["UpperTrunk_mass"], 2)).ljust(11),
        "|",
        "x: ",
        str(round(linkDimensions["UpperTrunk_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "y: ",
        str(round(linkDimensions["UpperTrunk_y"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "z: ",
        str(round(linkDimensions["UpperTrunk_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Lower Trunk            |",
        str(round(linkMass["LowerTrunk_mass"], 2)).ljust(11),
        "|",
        "x: ",
        str(round(linkDimensions["LowerTrunk_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "y: ",
        str(round(linkDimensions["LowerTrunk_y"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "z: ",
        str(round(linkDimensions["LowerTrunk_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Pelvis                 |",
        str(round(linkMass["Pelvis_mass"], 2)).ljust(11),
        "|",
        "x: ",
        str(round(linkDimensions["Pelvis_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "y: ",
        str(round(linkDimensions["Pelvis_y"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "z: ",
        str(round(linkDimensions["Pelvis_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Shoulder               |",
        str(round(linkMass["Shoulder_mass"], 2)).ljust(11),
        "|",
        "d: ",
        str(round(linkDimensions["Shoulder_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "l: ",
        str(round(linkDimensions["Shoulder_y"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Upper Arm              |",
        str(round(linkMass["UpperArm_mass"], 2)).ljust(11),
        "|",
        "d: ",
        str(round(linkDimensions["UpperArm_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "l: ",
        str(round(linkDimensions["UpperArm_y"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Fore Arm               |",
        str(round(linkMass["ForeArm_mass"], 2)).ljust(11),
        "|",
        "d: ",
        str(round(linkDimensions["ForeArm_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "l: ",
        str(round(linkDimensions["ForeArm_y"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Hand                   |",
        str(round(linkMass["Hand_mass"], 2)).ljust(11),
        "|",
        "x: ",
        str(round(linkDimensions["Hand_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "y: ",
        str(round(linkDimensions["Hand_y"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "z: ",
        str(round(linkDimensions["Hand_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Upper Leg              |",
        str(round(linkMass["UpperLeg_mass"], 2)).ljust(11),
        "|",
        "d: ",
        str(round(linkDimensions["UpperLeg_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "l: ",
        str(round(linkDimensions["UpperLeg_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Lower Leg              |",
        str(round(linkMass["LowerLeg_mass"], 2)).ljust(11),
        "|",
        "d: ",
        str(round(linkDimensions["LowerLeg_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "l: ",
        str(round(linkDimensions["LowerLeg_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
        "\n|Foot                   |",
        str(round(linkMass["Foot_mass"], 2)).ljust(11),
        "|",
        "x: ",
        str(round(linkDimensions["Foot_x"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "y: ",
        str(round(linkDimensions["Foot_y"], 2)).ljust(15),
        "|",
        "\n|                       |",
        "            |",
        "z: ",
        str(round(linkDimensions["Foot_z"], 2)).ljust(15),
        "|",
        "\n|-----------------------|-------------|---------------------|",
    )
